# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.mesh import router_pb2 as router__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in router_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SovereignMeshServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteBurst = channel.unary_unary(
                '/tordial.v1.SovereignMeshService/RouteBurst',
                request_serializer=router__pb2.RouteBurstRequest.SerializeToString,
                response_deserializer=router__pb2.RouteBurstResponse.FromString,
                _registered_method=True)
        self.StreamRouteBursts = channel.stream_stream(
                '/tordial.v1.SovereignMeshService/StreamRouteBursts',
                request_serializer=router__pb2.RouteBurstRequest.SerializeToString,
                response_deserializer=router__pb2.RouteBurstResponse.FromString,
                _registered_method=True)
        self.UpdateTelemetry = channel.unary_unary(
                '/tordial.v1.SovereignMeshService/UpdateTelemetry',
                request_serializer=router__pb2.TelemetryUpdateRequest.SerializeToString,
                response_deserializer=router__pb2.TelemetryUpdateResponse.FromString,
                _registered_method=True)
        self.GetSettlementStatus = channel.unary_unary(
                '/tordial.v1.SovereignMeshService/GetSettlementStatus',
                request_serializer=router__pb2.SettlementStatusRequest.SerializeToString,
                response_deserializer=router__pb2.SettlementStatusResponse.FromString,
                _registered_method=True)


class SovereignMeshServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RouteBurst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRouteBursts(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettlementStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SovereignMeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteBurst': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteBurst,
                    request_deserializer=router__pb2.RouteBurstRequest.FromString,
                    response_serializer=router__pb2.RouteBurstResponse.SerializeToString,
            ),
            'StreamRouteBursts': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRouteBursts,
                    request_deserializer=router__pb2.RouteBurstRequest.FromString,
                    response_serializer=router__pb2.RouteBurstResponse.SerializeToString,
            ),
            'UpdateTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTelemetry,
                    request_deserializer=router__pb2.TelemetryUpdateRequest.FromString,
                    response_serializer=router__pb2.TelemetryUpdateResponse.SerializeToString,
            ),
            'GetSettlementStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettlementStatus,
                    request_deserializer=router__pb2.SettlementStatusRequest.FromString,
                    response_serializer=router__pb2.SettlementStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tordial.v1.SovereignMeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tordial.v1.SovereignMeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SovereignMeshService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteBurst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tordial.v1.SovereignMeshService/RouteBurst',
            router__pb2.RouteBurstRequest.SerializeToString,
            router__pb2.RouteBurstResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRouteBursts(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tordial.v1.SovereignMeshService/StreamRouteBursts',
            router__pb2.RouteBurstRequest.SerializeToString,
            router__pb2.RouteBurstResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tordial.v1.SovereignMeshService/UpdateTelemetry',
            router__pb2.TelemetryUpdateRequest.SerializeToString,
            router__pb2.TelemetryUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettlementStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tordial.v1.SovereignMeshService/GetSettlementStatus',
            router__pb2.SettlementStatusRequest.SerializeToString,
            router__pb2.SettlementStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
